steps:
  # Step 1: Build & deploy Flask backend
  - name: 'gcr.io/cloud-builders/docker'
    dir: 'backend'
    args: [
      'build', '-t', 'gcr.io/$PROJECT_ID/hack-attack-backend', '.'
    ]

  - name: 'gcr.io/cloud-builders/gcloud'
    args: [
      'run', 'deploy', 'hack-attack-backend',
      '--image', 'gcr.io/$PROJECT_ID/hack-attack-backend',
      '--platform', 'managed',
      '--region', 'us-central1',
      '--allow-unauthenticated'
    ]

  # Step 2: Build React frontend
  - name: 'gcr.io/cloud-builders/npm'
    dir: 'frontend'
    args: ['install']

  - name: 'gcr.io/cloud-builders/npm'
    dir: 'frontend'
    args: ['run', 'build']

  # Step 3: Build & deploy React frontend as static site
  # (requires a Dockerfile in frontend/ or uses nginx to serve /build)
  - name: 'gcr.io/cloud-builders/docker'
    dir: 'frontend'
    args: [
      'build', '-t', 'gcr.io/$PROJECT_ID/hack-attack-frontend', '.'
    ]

  - name: 'gcr.io/cloud-builders/gcloud'
    args: [
      'run', 'deploy', 'hack-attack-frontend',
      '--image', 'gcr.io/$PROJECT_ID/hack-attack-frontend',
      '--platform', 'managed',
      '--region', 'us-central1',
      '--allow-unauthenticated'
    ]

images:
  - 'gcr.io/$PROJECT_ID/hack-attack-backend'
  - 'gcr.io/$PROJECT_ID/hack-attack-frontend'
